add_friend/urls.py
from django.conf.urls import url, include
from .views import index,add_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add', add_friend, name='add_friend'),
]

dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
 ]

linkensphere/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import view_profile.urls as view_profile
from view_profile.views import index as index_view_profile
import add_friend.urls as add_friend
import dashboard.urls as dashboard
import update_status.urls as update_status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include(dashboard,namespace='dashboard')),
    url(r'^view_profile/', include(view_profile, namespace='view_profile')),
    url(r'^add_friend/',include(add_friend,namespace="add_friend")),
	url(r'^update_status/', include(update_status, namespace='update_status')),
    url(r'^$', RedirectView.as_view(url='/update_status/', permanent=True), name='index'),
]

update_status/urls.py
from django.conf.urls import url
from .views import index
from .views import index, add_message

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_message', add_message, name='add_message'),
]

view_profile/urls.py
from django.conf.urls import url
from .views import index


urlpatterns = [
    url(r'^$', index, name='index'),
]

add_friend/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Friend(models.Model):
    name = models.CharField(max_length=27)
    link = models.URLField()
    created_date = models.DateTimeField(auto_now_add = True)

dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

update_status/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Message(models.Model):
	message = models.CharField(max_length=100)
	created_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.message

view_profile/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
    name = models.CharField(max_length=100)
    birthday = models.DateField()
    gender = models.CharField(max_length=10)
    expert = models.CharField(max_length=100)
    description = models.TextField()
    email = models.EmailField()
    created_at = models.DateTimeField(auto_now_add = True)

add_friend/forms.py
from django import forms

class Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    title_attrs = {
        'type': 'text',
        'placeholder':'Enter your friend\'s name...'
    }

    link_attrs = {
        'type': 'url',
        'placeholder':'Enter your friend\'s URL...'
    }

    name = forms.CharField(label='Name', required=True, max_length=27, widget=forms.TextInput(attrs=title_attrs))
    link = forms.URLField(label='URL', required=True, widget=forms.URLInput(attrs=link_attrs))

update_status/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'This field is required',
    }
    attrs = {
        'class': 'form'
    }
    message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True, label='')

add_friend/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import Friend
from django.shortcuts import render

# Create your views here.
response={}
def index(request):
    friends = Friend.objects.all()
    response['friends'] = friends
    html = 'add_friend.html'
    response['friend_form'] = Friend_Form
    return render(request, html, response)

def add_friend(request):
    form = Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['link'] = request.POST['link']
        friend = Friend(name=response['name'],link=response['link'])
        friend.save()
        return HttpResponseRedirect('/add_friend/')
    else:
        return HttpResponseRedirect('/add_friend/')

dashboard/views.py
from django.shortcuts import render
from view_profile.models import Profile
from update_status.models import Message
from add_friend.models import Friend
# Create your views here.

def index(request):
	feedCount = Message.objects.count()
	try:
		latestStatus = Message.objects.latest('created_date')
	except:
		latestStatus = ""
	try:
		profile = Profile.objects.get(pk=1)
	except:
		profile = None
	friendCount = Friend.objects.count()
	response = {'profile': profile, 'feedCount': feedCount, 'friendCount': friendCount, 'latestStatus': latestStatus}
	return render(request, 'dashboard.html', response)

update_status/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message

# Create your views here.

response = {}
def index(request):    
    message = Message.objects.order_by('-created_date')
    response['message'] = message
    html = 'update_status/update_status.html'
    response['message_form'] = Message_Form
    return render(request, html, response)

def add_message(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['message'] = request.POST['message']
        message = Message(message=response['message'])
        message.save()
        return HttpResponseRedirect('/update_status/')
    else:
        return HttpResponseRedirect('/update_status/')

view_profile/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import *
from .models import Profile

def index(request):
    profile = Profile.objects.get(pk=1)
    split_expertise = profile.expert.split(',') #Sleeping,marketing,Collector [sleeping,marketing,collector]
    response = {'profile':profile, 'split_expertise':split_expertise}
    return render(request, 'view_profile/view_profile.html', response)


# Birthday
# Gender
# Expertise : list
# Description
# Email

add_friend/templates/add_friend.html
{% extends "base.html" %}

{% block content %}
  <div class="friend">
    <h1>Add Friend</h1>
    <div class="addFriend">
      <form method="POST" action="add">
        {% csrf_token %}
        {{ friend_form }}
        <button id="submit" class="postButton" type="submit">Add Friend</button>
      </form>
    </div>
    <hr>
    <div class="listFriend">
      <h1>List Friend</h1>
      {% if friends %}
      <table>
        <th>Name</th>
        <th>URL</th>
        <th>Created Date</th>
        {% for friend in friends %}
        <tr>
          <td>{{friend.name}}</td>
          <td><a href="{{friend.link}}">{{friend.link|truncatechars:90}}</a></td>
          <td>Added {{friend.created_date}}</td>
        </tr>
        {% endfor %}
      </table>
      {% else %}
      <div class="alertNoFriend">
        <h1><strong>Oops!</strong> Tidak ada data friend.</h1>
      </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

dashboard/templates/dashboard.html
{% extends "base.html" %}
{% block content %}
<div class="profile">
  <img class="photo" src="../static/placeholderPhoto.jpg">
  <h1>{{ profile.name }}</h1>
  <h2><b>Friends:</b> {{ friendCount }}</h2>
  <h2><b>Feed:</b> {{ feedCount }} Posts</h2>
  <h2><b>Status:</b> {{ latestStatus }}
</div>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Linken's Sphere</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
</head>
<body>
  <div class="gradientHeader"></div>
  <div class="mobileNavigation" id="mobileNavigation">
    <a href="/update_status">Home</a>
    <a href="/view_profile">Profile</a>
    <a href="/add_friend">Friends</a>
    <a href="/dashboard">Dashboard</a>
  </div>
  <div class="mainContainer">
    <div class="navigationBar">
      <div class="hamburgerIcon" id="hamburgerIcon" onclick="toggleIcon()">
        <div class="hamburgerIconTop"></div>
        <div class="hamburgerIconBottom"></div>
      </div>
      <div class="logo">LINKEN'S SPHERE</div>
      <div class="navigation">
        <a href="/update_status">Home</a>
        <a href="/view_profile">Profile</a>
        <a href="/add_friend">Friends</a>
        <a href="/dashboard">Dashboard</a>
      </div>
    </div>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </div>
<script>
  function toggleIcon() {
    if (document.getElementById("hamburgerIcon").className === "hamburgerIcon") {
      document.getElementById("hamburgerIcon").className = "hamburgerIconAfter";
      document.getElementById("mobileNavigation").className = "mobileNavigationShow";
    } else {
      document.getElementById("hamburgerIcon").className = "hamburgerIcon";
      document.getElementById("mobileNavigation").className = "mobileNavigation";
    }
  }
</script>
</body>
</html>

update_status/templates/update_status/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="UPDATE STATUS">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="{% static 'css/update_status.css' %}" rel="stylesheet">    

    <title> 
        {% block title %} Lingin By {{author}}{% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "update_status/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "update_status/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

update_status/templates/update_status/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p>&copy; Made with Love by {{author}}</p>

update_status/templates/update_status/partials/header.html
<!-- templates/lab_5/partials/header.html -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Lingin</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a href="{% url 'update_status:index' %}#input-list">Input Todo</a></li>
        <li><a href="{% url 'update_status:index' %}#my-list">My List</a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
...

update_status/templates/update_status/update_status.html
{% extends "base.html" %}

{% block content %}
<div class="status">
        <h2>What's Happening?</h2>
    <form id="form" method="POST" action="{% url 'update_status:add_message' %}">
        {% csrf_token %}
		<div class="writeStatusContainer">{{message_form}}</div>
        <button class="postButton" type="submit" >Post</button>
        <br>
    </form>
    {% if message %}
        {% for data in message %}
            <div class="statusContainer">
                <span class="date">{{data.created_date|date:"d M Y G:i:s"}}</span>
                <span>{{data.message}}</span>
            </div>
        {% endfor %}
    {% endif %}
</div>

{% endblock %} 

view_profile/templates/view_profile/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="LAB 4">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

    <title>
        {% block title %} Profile {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "view_profile/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <br>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

view_profile/templates/view_profile/partials/footer.html
<p align="center">&copy; {{author}}</p>

view_profile/templates/view_profile/partials/header.html
   <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'view_profile:index' %}">Ling In</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <!-- LINK MENUJU table, dan link menuju home#form -->
            <li><a href="{% url 'view_profile:index' %}#form"> Status </a></li>
            <li><a href="{% url 'view_profile:index' %}"> Profile </a> </li>
            <li><a href="{% url 'view_profile:index' %}#form"> Friends </a></li>
            <li><a href="{% url 'view_profile:index' %}"> Stats </a> </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

view_profile/templates/view_profile/view_profile.html
{% extends "base.html" %}
{% block content %}

<style>
.expert {
  border: 1px solid lightgray;
  padding: 0.4rem;
  margin: 0.2 rem;
  border-radius: 1rem;
  font-size: 0.8rem;
  color: gray;
}
</style>

<div class="profile">
  <img class="photo" src="../static/placeholderPhoto.jpg">
  <p><b>{{ profile.name }}</b></p>
  <p><b>Birthday: </b>{{ profile.birthday|date:"d M"}}</p>
  <p><b>Gender: </b>{{ profile.gender }}</p>
  <p><b>Expertise: </b>{% for ii in split_expertise %} <span class="expert">{{ ii }}</span> {% endfor %}</p>
  <p><b>Description: </b>{{ profile.description }}</p>
  <p><b>Email: </b>{{ profile.email }}</p>
</div>
{% endblock %}